In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.2.1


In [11]:
hello = tf.constant("hello ")
print(type(hello))

<class 'tensorflow.python.framework.ops.Tensor'>


In [12]:
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [13]:
world = tf.constant("Tensorflow")


In [14]:
print(world)

Tensor("Const_3:0", shape=(), dtype=string)


In [15]:
type(world)

tensorflow.python.framework.ops.Tensor

In [16]:
with tf.Session() as sess:
    result = sess.run(hello+world)
    

In [17]:
print(result)

b'hello Tensorflow'


In [20]:
# addition of two numbers in tf

a = tf.constant(10)
b = tf.constant(40)

with tf.Session() as sess:
    result = sess.run(a+b)
    


In [21]:
print(result)

50


In [24]:
const = tf.constant(10) # constant variable

fill_mat = tf.fill((4,4),10)

my_zeors = tf.zeros((4,4))

my_ones = tf.ones((4,4))

my_randn = tf.random_normal((4,4),mean=0,stddev=1)

my_randu = tf.random_uniform((4,4),minval=0,maxval=1)



In [25]:
my_ops = [const,fill_mat,my_zeors,my_ones,my_randn,my_randu]


In [28]:
sess = tf.InteractiveSession()  # for notebook setting

for ops in my_ops:
    print(sess.run(ops))  # or we can use print(ops.eval()), we get same result
    print("\n")
    


10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.53517067  1.68033004  0.10939591 -0.94361228]
 [ 0.87713176  1.01586378  0.2130418   0.02944321]
 [ 0.07864566 -2.17654967 -0.18237607 -0.94440442]
 [-0.17934813  1.50365841  1.53597236  1.08801675]]


[[ 0.32750916  0.25780511  0.93643677  0.60807896]
 [ 0.62692094  0.79275227  0.72725523  0.6728524 ]
 [ 0.67395711  0.25177526  0.77787399  0.86361718]
 [ 0.7743094   0.66982949  0.16354084  0.79913545]]




In [29]:
# matrix multiplication in tf

a = tf.constant([[1,2],
                [3,4]])


In [30]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [31]:
b = tf.constant([[10],[100]])


In [32]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [33]:
# multiplication

c = tf.matmul(a,b)

sess.run(c)


array([[210],
       [430]], dtype=int32)

In [34]:
c.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
c.eval()

array([[210],
       [430]], dtype=int32)